title: ask-rb
description: >-
  A Ruby ecosystem for building LLM-powered applications —
  web agents, coding assistants, desktop apps, and automated workflows.
url: "https://ask-rb.github.io"
baseurl: "/ask-docs"
repository: ask-rb/ask-docs

theme: just-the-docs

aux_links:
  "ask-rb on GitHub":
    - "https://github.com/ask-rb"

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple


just_the_docs:
  nav_sort: case_sensitive
sass:
  quiet_deps: true
  silence_deprecations:
    - color-functions
    - import
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
