source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "just-the-docs"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-github-metadata"
gem "webrick"

# Gems the runnable docs examples execute against (CI verify runs without
# the sibling ask-rb repos, so the examples resolve from RubyGems here).
gem "ask"
gem "ask-auth"
gem "ask-agent"
gem "ask-eval"
gem "ask-graph"
gem "ask-llm-providers"
gem "ask-mcp"
gem "ask-observability"
gem "ask-opentelemetry"
gem "ask-rag"
gem "ask-sandbox-providers"
gem "ask-schema"
gem "ask-state-providers"
gem "ask-tools"
gem "ask-tools-shell"
gem "ask-web-fetch"
gem "ask-web-search"
gem "sqlite3"
gem "ostruct"
